### ISSUE TITLE
Is there a way to assign an id to a Textfield?

### ISSUE THREAD

**Issue by samueller** [MichaelCombs28/elm-mdl#3]
Not sure if this is the new elm-mdl place to ask questions like these...

I've tried the following:
```
Textfield.render Mdl [0] model.mdl
  [ Material.Options.id "my-id" ]
```
The problem is that assigns `my-id` as the `id` of the wrapping `<div>`:
```
<div id="my-id" class="mdl-js-textfield mdl-textfield">
  <input class="mdl-textfield__input" type="text" style="outline: none;">
</div>
```
I need for the actual `input` element to have an `id`.

**Comment by MichaelCombs28** [comment]
Textfield.render
        [  ..
        ,  Options.inner
            [ Options.id "myId" ]
        ]

http://package.elm-lang.org/packages/MichaelCombs28/elm-mdl/1.0.1/Material-Options#inner

**Comment by samueller** [comment]
This is exactly what I was looking for. Surprised I overlooked `Options.inner` while perusing the API. Curious why this issue was reopened?
