### ISSUE TITLE
CSS not Loading

### ISSUE THREAD

**Issue by kittykatattack** [MichaelCombs28/elm-mdl#6]
Hi Michael,

Just quick question:
I installed your fork and everything compiles and works.
The only problem is the mdl css is not being applied.
(The components are there, and they work, they're just not styled.)
As far as you know, do I need to link to material.min.css in the html document head?\

Thanks!

**Comment by MichaelCombs28** [comment]
Have you tried

```elm
main =
    program
      { ...
      , view = view |> Material.Scheme.top
      }
```

Check out the `Material.Scheme` module. Otherwise I've just tested it and it seems to work.

If you want to use elm-reactor use this method, otherwise a link in the head tag works too.

**Comment by kittykatattack** [comment]
Thanks Michael, that worked! 
I added `|> Material.Scheme.top` to the end of my `view` function and that did the trick.
Thanks for all your work on this fork!!
